// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoeGmlEPvKQtrggjppjJZpOm7Yu8b1Cc',
    appId: '1:262039134878:web:1802571fc1d83155fd518f',
    messagingSenderId: '262039134878',
    projectId: 'flutter-fcm-4e462',
    authDomain: 'flutter-fcm-4e462.firebaseapp.com',
    storageBucket: 'flutter-fcm-4e462.firebasestorage.app',
    measurementId: 'G-6F1QH6MDN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgod4PiiEntruFE93xDz3nhANXScnfHFg',
    appId: '1:262039134878:android:b2c4b4f2c80ad667fd518f',
    messagingSenderId: '262039134878',
    projectId: 'flutter-fcm-4e462',
    storageBucket: 'flutter-fcm-4e462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKg9TxMc17Lqu0WsVDDXNIb7YMynNA21Y',
    appId: '1:262039134878:ios:6c8c346a35818dbefd518f',
    messagingSenderId: '262039134878',
    projectId: 'flutter-fcm-4e462',
    storageBucket: 'flutter-fcm-4e462.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKg9TxMc17Lqu0WsVDDXNIb7YMynNA21Y',
    appId: '1:262039134878:ios:6c8c346a35818dbefd518f',
    messagingSenderId: '262039134878',
    projectId: 'flutter-fcm-4e462',
    storageBucket: 'flutter-fcm-4e462.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvoeGmlEPvKQtrggjppjJZpOm7Yu8b1Cc',
    appId: '1:262039134878:web:707794de87d6b133fd518f',
    messagingSenderId: '262039134878',
    projectId: 'flutter-fcm-4e462',
    authDomain: 'flutter-fcm-4e462.firebaseapp.com',
    storageBucket: 'flutter-fcm-4e462.firebasestorage.app',
    measurementId: 'G-T0WJV7JM3C',
  );
}
